In [2]:
import pandas as pd
df = pd.read_csv("fading_data.csv") #importing csv file in
df.head() #checking import worked by looking at first first 5 rows

   group  bg_reading  bead_size bead_number  scf_bead  raw_bead  mean_control
0    1.0    0.206917        1.0         1_1  0.976572     67.49      0.611921
1    1.0    0.206917        1.0         1_2  0.976812     56.99      0.611921
2    1.0    0.206917        1.0         1_3  0.978980     54.90      0.611921
3    1.0    0.206917        1.0         1_4  0.928171     53.84      0.611921
4    1.0    0.206917        1.0         1_5  0.916388     55.39      0.611921

In [3]:
#data in the table that doesnt have both and experimental value and an scf value is removed
print("Rows before:", len(df)) #number of rows before 
df = df.dropna(subset=["raw_bead"]) #rows with no experimental variable value are removed
print("Rows after:", len(df)) #number of rows after to verify removal
print(df["raw_bead"].isna().sum()) #should show 0 if no rows with missing values remain
df.to_csv("cleaned_fading_data.csv", index=False) #new beads_data file with unwanted values removed, saved to file

Rows before: 150
Rows after: 138
0

In [4]:
#next calculating calibrated counts using the scf values and raw bead counts
df['raw_bead'] = pd.to_numeric(df['raw_bead'], errors='coerce') #data needs to be classed as numeric
df['calibrated_count'] = df['scf_bead'] * df['raw_bead'] #calculating calibrated counts
df.to_csv("fading_data_with_calibrated_counts.csv", index=False) #saving new dataframe with calibrated counts to csv file
df.head()

,group,bg_reading,bead_size,bead_number,scf_bead,raw_bead,mean_control,calibrated_count
0,1.0,0.206917,1.0,1_1,0.976572,67.49,0.611921,65.908824
1,1.0,0.206917,1.0,1_2,0.976812,56.99,0.611921,55.668515
2,1.0,0.206917,1.0,1_3,0.978980,54.90,0.611921,53.745989
3,1.0,0.206917,1.0,1_4,0.928171,53.84,0.611921,49.972704
4,1.0,0.206917,1.0,1_5,0.916388,55.39,0.611921,50.758706

In [5]:
#calulating adjusted counts using the mean control values and calibrated counts
df['adjusted_count'] = df['scf_bead'] * (df['raw_bead'] - df['mean_control'])
df.to_csv("fading_data_with_adjusted_counts.csv", index=False) #saving new dataframe with adjusted counts to csv file
df.head()

,group,bg_reading,bead_size,bead_number,scf_bead,raw_bead,mean_control,calibrated_count,adjusted_count
0,1.0,0.206917,1.0,1_1,0.976572,67.49,0.611921,65.908824,65.311240
1,1.0,0.206917,1.0,1_2,0.976812,56.99,0.611921,55.668515,55.070783
2,1.0,0.206917,1.0,1_3,0.978980,54.90,0.611921,53.745989,53.146930
3,1.0,0.206917,1.0,1_4,0.928171,53.84,0.611921,49.972704,49.404737
4,1.0,0.206917,1.0,1_5,0.916388,55.39,0.611921,50.758706,50.197950

In [19]:
# keeping columns numeric 
df['adjusted_count'] = pd.to_numeric(df['adjusted_count'], errors='coerce')
df['raw_bead'] = pd.to_numeric(df['raw_bead'], errors='coerce')